config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root :to => 'top#index'
  resources :users do
    resources :id
  end
  get '/home/about', to: 'about#index'
  resources :books do
    resources :id
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  attachment :book_image
  validates :title, presence:{ message: "can't be blank error" }
  validates :body, presence: { message: "can't be blank error" }, length: { in: 0..200 }
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :name, uniqueness: true, presence:true, length: { in: 2..20 }
  validates :introduction,    length: { maximum:50 } 
  attachment :profile_image
  has_many :books, dependent: :destroy
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  def after_sign_in_path_for(resource)
    user_path(current_user) # ログイン後に遷移するpathを設定
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :name])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!,except: [:top]

  def index
    @user = User.find(current_user.id)
    @books = Book.all
    @book = Book.new
  end
  def show
    @newBook = Book.new
    @book = Book.find(params[:id])
    @user = User.find(@book.user_id)
  end

  def edit 
    @book = Book.find(params[:id])
    if @book.user_id == current_user.id.to_s
    else
      redirect_to books_path
    end
  end
  def update
    @book = Book.find(params[:id])
    @valid = Book.find(params[:id])
    if @valid.update(book_params)
      redirect_to book_path(params[:id]), notice: "You have updated user successfully."
    else 
      render :edit
    end
  end
  def create
    book = Book.new(book_params)
    if book.save
      redirect_to book_path(book.id), notice: "You have updated user successfully."
    else
      @user = User.find(current_user.id)
      @books = Book.all
      @valid = book
      render :index
    end
  end
  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end  
  private
  def book_params
    params.require(:book).permit(:title,:body,:book_image).merge(user_id: current_user.id)
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!,except: [:top]

  def index

    @userId = current_user.id
    @user = User.find(current_user.id)
    @users = User.all
    @book = Book.new

  end
  def show
    @user = User.find(params[:id])
    @book = Book.new();
    
    @books = Book.where(user_id: params[:id])
    
  end
  def edit
    if params[:id] == current_user.id.to_s
      @user = User.find(params[:id])
    else 
      redirect_to user_path(current_user.id)
    end

 
  end
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user.id), notice: "You have updated user successfully."
    else
      render :edit
    end
  end
  private

  def user_params
    params.require(:user).permit(:introduction, :name, :profile_image)
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/about/index.html.erb
<div class="container">
  <div class="row">
    <h1 class="px-3 mx-auto">Welcome to <i class="fas fa-book"></i><strong>Bookers</strong>!</h1>
  </div>
</div>

app/views/books/edit.html.erb
<h1>Book#edit</h1>
<p>Find me in app/views/books/edit.html.erb</p>
<h2>Editing Book</h2>
<div class="container">  <!-- この行を追加 -->
  <div class="row">   
    <%= form_with model:@book, local:true do |f| %>
    <div class="col-lg-12">
    <label for="inputName">Name</label>
    <%= f.text_field :title, autofocus: true, id:"title", placeholder:"title"%>
    </div>
    <div class="col-lg-12">

    <label for="introduction">感想</label>
    <%= f.text_field :body, autofocus: true, id:"body", placeholder:"感想"%>
    </div>
    <div class="col-lg-12">
    <label for="inputImage">ProfileImage</label>
    <%= attachment_image_tag @book, :book_image, :fill, 60, 60, fallback: "no_image.jpg"%>
    </div>
    <div class="col-lg-12">
    
    <%= f.attachment_field :book_image, placeholder: "プロフィール画像" %>  
    <%= f.submit "Update Book" %>
    </div>
    <% end %>
    <div class="col-lg-12">

    <%= link_to 'Show', book_path(@book) %>
    <%= link_to 'Back', books_path %>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<p id="notice"></p>
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <h2>User info</h2>
      <%= attachment_image_tag @user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg"%>
<table class="table">

<tbody><tr></tr>
  <tr>
	  <th>name</th>
	  <th><%= @user.name %></th>
  </tr>
  <tr>
	  <th>introduction</th>
	  <th><%= @user.introduction %></th>
  </tr>
</tbody></table>
　
<div class="row">
        <%= link_to "", edit_user_path(@user),class:"btn btn-outline-secondary btn-block fas fa-user-cog" %>
</div>
      <%= form_with url: books_path, model: @book, local:true do |f| %>
      <h2 class="mt-3">New book</h2>
      <label for="book_title">Title</label>
      <div class="form-group">
      <%= f.text_field :title,class:"form-control" %>
      </div>
      <div class="form-group">
      <label for="book_opinion">Opinion</label>
      <%= f.text_area :body,class:"form-control" %>
      </div>
      <div class="form-group">
      <%= f.submit 'Create Book',class:"btn btn-success" %>
      </div>
      <% end %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
      <% @books.each do |book| %>
        <tr>
          <td><%= link_to attachment_image_tag(book, :book_image, :fill, 60, 60, fallback: "no_image.jpg"),user_path(book.user_id)%></td>
          <td><%= link_to book.title, book_path(book) %></td>
          <td><%= book.body %></td>
        </tr>
      <% end %>
  </tbody>
</table>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<p id="notice"></p>
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <h2>User info</h2>
      <%= attachment_image_tag @user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg"%>
<table class="table">

<tbody><tr></tr>
  <tr>
	  <th>name</th>
	  <th><%= @user.name %></th>
  </tr>
  <tr>
	  <th>introduction</th>
	  <th><%= @user.introduction %></th>
  </tr>
</tbody></table>



<div class="row">
        <%= link_to "", edit_user_path(@user),class:"btn btn-outline-secondary btn-block fas fa-user-cog" %>
</div>
      <%= form_with url: books_path, model: @newBook, local:true do |f| %>
      <h2 class="mt-3">New book</h2>
      <label for="book_title">Title</label>
      <div class="form-group">
      <%= f.text_field :title,class:"form-control" %>
      </div>
      <div class="form-group">
      <label for="book_opinion">Opinion</label>
      <%= f.text_area :body,class:"form-control" %>
      </div>
      <div class="form-group">
      <%= f.submit 'Create Book',class:"btn btn-success" %>
      </div>
      <% end %>
</div>
<div class="col-md-8 offset-md-1">
  		<h2>Book detail</h2>
  		<table class="table">
  		  <tbody>
  		    <tr>
          <td><%= link_to attachment_image_tag(@book,:book_image, :fill, 60, 60, fallback: "no_image.jpg"), user_path(@book.user_id)%><br><%= link_to @user.name, user_path(@book.user_id) %></td>
          <td><%= link_to @book.title,book_path(@book) %></td>
          <td><%= @book.body %></td>
          <td></td>

          <% if @book.user_id == current_user.id.to_s then %>
            <td><%= link_to "Edit"  ,edit_book_path(@book.id)%></td>
            <td><%= link_to "Destroy" ,book_path(@book.id), :method => :delete%></td>
          <% else %>

          <% end %>
        </tr>
      </tbody></table>
    </div>
  </div>
</div>

app/views/layouts/_error.html.erb
<% if @valid %>
  <div id="error_explanation" class="alert alert-danger">
    <ul>
      <% @valid
      .errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_notifications.html.erb
<% flash.each do |key, value| %>
  <%= content_tag(:div, value, class: "#{key}") %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Project</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/a46c6f0a0d.js" crossorigin="anonymous"></script>
  </head>

  <body>

    <header>

      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <%= link_to "Bookers", root_path, class: 'navbar-brand' %>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
            <% if user_signed_in? %>
            <li class="nav-item">
              <%= link_to "Home", user_path(current_user), class:"fas fa-home nav-link text-light" %>
            <li class="nav-item">
              <%=  link_to "users", users_path, class: 'fas fa-users nav-link text-light' %>
            </li>
            <li class="nav-item">

              <%= link_to "books", books_path, class: 'fas fa-book-open nav-link text-light' %>
            <li class="nav-item">
              <%= link_to "logout", destroy_user_session_path, method: :delete, class: 'fas fa-sign-out-alt nav-link text-light' %>
            </li>
            <% else %>
            <li>
              <%= link_to "Home", root_path, class:"fas fa-home nav-link text-light" %>
            </li>
            <li>
              <%= link_to "About","/home/about",class:"fas fa-link nav-link text-light" %>
            </li>
            <li class="nav-item">
              <%= link_to "sign up", new_user_registration_path, class:"fas fa-user-plus nav-link text-light" %>
            </li>
            <li class="nav-item">
              <%= link_to "login", new_user_session_path, class:"fas fa-sign-in-alt nav-link text-light" %>
            </li>
            <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <%= render 'layouts/error' %>
    <%= render 'layouts/notifications' %>

    <%= yield %>
    <footer>
  <div class="container mt-5">
  	<div class="row">
    	<div class="mx-auto">
    		<p>CopyRight Infratop.inc</p>
    	</div>
    </div>
  </div>
</footer>
  </body>
</html>

app/views/top/index.html.erb
<div class="container">
  <div class="row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
      <h1>welcome to <i class="fas fa-book"></i><strong>Bookers</strong>  !!</h1>
      <p>In  <i class="fas fa-book"></i><strong>Bookers</strong>, </p>
      <p>you can share and exchange  your opinions , inpressions , and emotions</p>
      <p> about various books!</p>
      <div class="btn-wrapper col-10 mx-auto">
        <div class="row">
          <%= link_to "Log in", new_user_session_path, class: 'btn btn-info btn-sm btn-block mb-3 sign_in' %>
        </div>
        <div class="row">
          <%= link_to "Sign Up", new_user_registration_path, class: 'btn btn-success btn-sm btn-block sign_up' %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<% if @user.errors.any? %>
  <%= @user.errors.count %>件のエラーが発生しました
  <% @user.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>

<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>User info</h2>
    <%= form_with model:@user, local:true do |f| %>
    　<div class="form-group">
      <label for="inputName">Name</label>
      <%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"名前" ,class:"form-control name"%>
      </div>
      <div class="form-group">
      <label for="inputImage">Image</label>
      <%= f.attachment_field :profile_image, placeholder: "プロフィール画像",class:"form-control-file user_image" %>  
      </div>
      <div class="form-group">
      <label for="introduction">Introduction</label>
      <%= f.text_area :introduction, autofocus: true, id:"inputIntroduction", placeholder:"自己紹介",class:"form-control introduction"%>
      </div>
      <div class="form-group">
      <%= f.submit "Update User",class:"btn btn-secondary" %>
      </div>
    <% end %> </div>
</div>

      </div>

app/views/users/index.html.erb
<p id="notice"></p>
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <h2>User info</h2>
      <%= attachment_image_tag @user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg"%>
<table class="table">

<tbody><tr></tr>
  <tr>
	  <th>name</th>
	  <th><%= @user.name %></th>
  </tr>
  <tr>
	  <th>introduction</th>
	  <th><%= @user.introduction %></th>
  </tr>
</tbody></table>
　
<div class="row">
        <%= link_to "", edit_user_path(@user),class:"btn btn-outline-secondary btn-block fas fa-user-cog" %>
</div>
      <%= form_with url: books_path, model: @book, local:true do |f| %>
      <h2 class="mt-3">New book</h2>
      <label for="book_title">Title</label>
      <div class="form-group">
      <%= f.text_field :title,class:"form-control" %>
      </div>
      <div class="form-group">
      <label for="book_opinion">Opinion</label>
      <%= f.text_area :body,class:"form-control" %>
      </div>
      <div class="form-group">
      <%= f.submit 'Create Book',class:"btn btn-success" %>
      </div>
      <% end %>

    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Users</h2>
      <table class="table table-hover table-inverse">
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th></th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
         <% @users.each do |user| %>
        <tr>
          <td><%= link_to attachment_image_tag(user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg"), user_path(user)%></td>
          <td><%= user.name %></td>
          <td><%= link_to 'Show', user %></td>
        </tr>
      <% end %>
  </tbody>
</table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<p id="notice"></p>
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <h2>User info</h2>
      <%= attachment_image_tag @user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg"%>
<table class="table">

<tbody><tr></tr>
  <tr>
	  <th>name</th>
	  <th><%= @user.name %></th>
  </tr>
  <tr>
	  <th>introduction</th>
	  <th><%= @user.introduction %></th>
  </tr>
</tbody></table>
　
<div class="row">
        <%= link_to "", edit_user_path(@user),class:"btn btn-outline-secondary btn-block fas fa-user-cog" %>
</div>
      <%= form_with url: books_path, model: @book, local:true do |f| %>
      <h2 class="mt-3">New book</h2>
      <label for="book_title">Title</label>
      <div class="form-group">
      <%= f.text_field :title,class:"form-control" %>
      </div>
      <div class="form-group">
      <label for="book_opinion">Opinion</label>
      <%= f.text_area :body,class:"form-control" %>
      </div>
      <div class="form-group">
      <%= f.submit 'Create Book',class:"btn btn-success" %>
      </div>
      <% end %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
  <thead>
    <tr>
      <th></th>
      <th>title</th>
      <th>opinion</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
      <% @books.each do |book| %>
        <tr>
          <td><%= link_to attachment_image_tag(book, :book_image, :fill, 60, 60, fallback: "no_image.jpg"), user_path(@user)%></td>
          <td><%= link_to book.title,book_path(book) %></td>
          <td><%= book.body %></td>
          
          <% if book.user_id == current_user.id.to_s then %>
            <td><%= link_to 'Show', book %></td>
            <td><%= link_to 'Edit', edit_book_path(book) %></td>
            <td><%= link_to 'Destroy', book_path(book), method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% else %>
          <% end %>
      <% end %>
  </tbody>
</table>
    </div>
  </div>
</div>